const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);let conversationId='',currentStudent='demo-student';const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function typesetMath(element){
  if(!element)return;
  try{
    if(window.MathJax?.startup?.promise)await window.MathJax.startup.promise;
    if(window.MathJax?.typesetPromise)await window.MathJax.typesetPromise([element]);
    else element.classList.add('mathPending');
  }catch(error){element.classList.add('mathPending');console.warn('Math rendering failed',error)}
}
const mathObserver=new MutationObserver(mutations=>mutations.forEach(mutation=>mutation.addedNodes.forEach(node=>{
  if(node.nodeType===Node.ELEMENT_NODE&&node.matches?.('.message.ai'))typesetMath(node);
})));
mathObserver.observe($('#messages'),{childList:true});
const renderMarkdown=s=>escapeHtml(s).replace(/^### (.+)$/gm,'<h4>$1</h4>').replace(/^## (.+)$/gm,'<h3>$1</h3>').replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/^- (.+)$/gm,'<span class="mdBullet">• $1</span>').replace(/\n/g,'<br>');
const titles={tutor:'今天想弄懂什么？',graph:'沿着知识路径学习',profile:'看见每一步成长',practice:'练会才是真的会',teacher:'让教学决策有依据',history:'把成长留在这里'};
function switchView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===name));$$('.nav').forEach(v=>v.classList.toggle('active',v.dataset.view===name));$('#pageTitle').textContent=titles[name];if(name==='graph')loadGraph();if(name==='profile')loadProfile();if(name==='practice')loadPractice();if(name==='teacher')loadTeacher();if(name==='history')loadHistory()}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
fetch('/api/health').then(r=>r.json()).then(d=>$('#engine').textContent=d.engine).catch(()=>$('#engine').textContent='离线演示模式');
$('#newChat').onclick=()=>{conversationId='';$('#messages').innerHTML='<div class="welcome"><strong>✦</strong><h2>新对话已创建</h2><p>告诉我你想学习的知识点。</p></div>'};
fetch('/api/users').then(r=>r.json()).then(users=>{$('#userSelect').innerHTML=users.filter(x=>x.role==='student').map(x=>`<option value="${x.id}">${x.grade} · ${x.name}</option>`).join('')});$('#userSelect').onchange=e=>{currentStudent=e.target.value;conversationId='';loadProfile()};
$$('.prompts button').forEach(b=>b.onclick=()=>{$('#query').value=b.textContent;send()});
$('#send').onclick=send;$('#query').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});
function addMessage(kind,content,extra={}){const box=document.createElement('div');box.className='message '+kind;if(kind==='user')box.textContent=content;else{const grounded=extra.validation?.grounded||extra.validation?.retrieval_grounded;const verified=grounded?'✓ 检索证据核验通过':'△ 建议教师复核';box.innerHTML=`<div class="meta"><b>✦ 如意智学</b><span>${extra.engine||''} · 置信度 ${Math.round((extra.confidence||0)*100)}%</span></div><p></p><div class="verify ${grounded?'ok':''}">${verified}</div>`;box.querySelector('p').innerHTML=renderMarkdown(content);if(extra.learning_path?.length){const path=document.createElement('div');path.className='path';path.innerHTML='<b>推荐学习路径</b> '+extra.learning_path.map(x=>escapeHtml(x.name)).join(' → ');box.appendChild(path)}if(extra.sources?.length){const sources=document.createElement('div');sources.className='sources';extra.sources.forEach((s,i)=>{sources.innerHTML+=`<div class="source"><b>[${i+1}] ${escapeHtml(s.title)}</b> · 匹配 ${s.score}<br>${escapeHtml(s.excerpt||s.source||'')}</div>`});box.appendChild(sources)}const actions=document.createElement('div');actions.className='answerActions';actions.innerHTML='<button>复制</button><button>收藏</button><button>👍 有帮助</button><button>⚑ 待改进</button>';const buttons=actions.querySelectorAll('button');buttons[0].onclick=()=>navigator.clipboard.writeText(content);buttons[1].onclick=()=>fetch('/api/favorites',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({student_id:currentStudent,title:extra.sources?.[0]?.title||'辅导回答',content,source:extra.sources?.[0]?.source||''})});buttons[2].onclick=()=>sendFeedback('helpful',content);buttons[3].onclick=()=>sendFeedback('needs_improvement',content);box.appendChild(actions)}$('#messages').appendChild(box);box.scrollIntoView({behavior:'smooth'})}
function sendFeedback(rating,query){return fetch('/api/teacher/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({student_id:currentStudent,query,rating})})}
async function send(reveal=false){const q=$('#query').value.trim()||(reveal?'请继续完整讲解':'');if(!q)return;$('.welcome')?.remove();if(!reveal)addMessage('user',q);$('#query').value='';$('#send').disabled=true;const loading=document.createElement('div');loading.className='message ai';loading.textContent='正在检索课程知识、前置概念与学习状态…';$('#messages').appendChild(loading);try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:q,student_id:currentStudent,subject:$('#subject').value,grade:'八年级',mode:$('#mode').value,conversation_id:conversationId,reveal_answer:reveal})});const d=await r.json();conversationId=d.conversation_id||conversationId;loading.remove();addMessage('ai',d.answer,d);if(d.stage==='hint'){const btn=document.createElement('button');btn.className='reveal';btn.textContent='查看完整讲解';btn.onclick=()=>send(true);$('#messages').appendChild(btn)}}catch(e){loading.textContent='服务暂时不可用，请确认后端已启动。'}finally{$('#send').disabled=false}}
async function loadGraph(){if($('#graphCanvas').children.length)return;const data=await fetch('/api/graph').then(r=>r.json()),canvas=$('#graphCanvas');const names=Object.fromEntries(data.nodes.map(n=>[n.id,n.name]));['数学','物理'].forEach(subject=>{const lane=document.createElement('div');lane.className='graphLane '+(subject==='物理'?'physicsLane':'');lane.innerHTML=`<div class="laneTitle"><b>${subject}</b><span>基础概念 → 核心方法 → 综合应用</span></div><div class="conceptGrid"></div>`;const grid=lane.querySelector('.conceptGrid');data.nodes.filter(n=>n.subject===subject).sort((a,b)=>a.level-b.level||a.name.localeCompare(b.name,'zh-CN')).forEach(n=>{const prerequisites=data.edges.filter(e=>e.target===n.id&&e.relation==='前置').map(e=>names[e.source]);const card=document.createElement('button');card.className='conceptCard';card.dataset.id=n.id;card.innerHTML=`<small>L${n.level||1}</small><b>${n.name}</b><span>${prerequisites.length?'前置：'+prerequisites.join('、'):'基础知识点'}</span>`;card.onclick=()=>{const related=new Set([n.id]);data.edges.forEach(e=>{if(e.source===n.id||e.target===n.id){related.add(e.source);related.add(e.target)}});$$('.conceptCard').forEach(x=>x.classList.toggle('related',related.has(x.dataset.id)));$('#graphPath').textContent=prerequisites.length?`${prerequisites.join(' → ')} → ${n.name}`:`${n.name}（基础起点）`};grid.appendChild(card)});canvas.appendChild(lane)});const path=document.createElement('div');path.id='graphPath';path.className='graphPath';path.textContent='点击知识点查看直接前置与关联路径';canvas.prepend(path)}
async function loadProfile(){const d=await fetch('/api/profile/'+currentStudent).then(r=>r.json());$('#overall').textContent=d.overall;$('#bars').innerHTML=d.mastery.map(m=>`<div class="bar"><span>${m.name}</span><div class="track"><div class="fill" style="width:${m.mastery}%"></div></div><b>${m.mastery}%</b></div>`).join('');$('#recommendation').textContent=`优先巩固「${d.recommended.name}」。建议先复习前置概念，再完成 3 道由易到难的练习。学习路径：${d.learning_path.map(x=>x.name).join(' → ')}`}
async function loadTeacher(){const [d,issues,knowledge]=await Promise.all([fetch('/api/teacher/overview').then(r=>r.json()),fetch('/api/teacher/quality-issues').then(r=>r.json()),fetch('/api/teacher/knowledge').then(r=>r.json())]);$('#studentCount').textContent=d.student_count;$('#classAverage').textContent=d.class_average+'%';$('#questionCount').textContent=d.questions;$('#lowConfidence').textContent=d.low_confidence;$('#weakConcepts').innerHTML=d.weak_concepts.map(x=>`<div class="weak"><span>${x.name}<small>${x.students} 名学生有记录</small></span><div class="track"><div class="fill" style="width:${x.mastery}%"></div></div><b>${x.mastery}%</b></div>`).join('');$('#recentQuestions').innerHTML=d.recent_questions.length?d.recent_questions.map(x=>`<div><span>${x.query}</span><small>${x.concept_id} · ${Math.round(x.confidence*100)}%</small></div>`).join(''):'<p>学生开始提问后，这里会显示可复核记录。</p>';$('#qualityIssues').innerHTML=issues.length?issues.map(x=>`<div><span>${x.issue_type} · ${x.query.slice(0,35)}</span><small>${x.status}</small></div>`).join(''):'<p>暂无待处理问题。</p>';$('#knowledgeStatus').innerHTML=`<div><span>结构化课程条目</span><b>${knowledge.length}</b></div><div><span>检索切片总数</span><b>79+</b></div>`}
async function loadHistory(){const [history,favorites]=await Promise.all([fetch('/api/history/'+currentStudent).then(r=>r.json()),fetch('/api/favorites/'+currentStudent).then(r=>r.json())]);$('#historyList').innerHTML=history.length?history.map(x=>`<div><span>${x.role==='user'?'我':'如意智学'}：${escapeHtml(x.content.slice(0,70))}</span><small>${new Date(x.created_at).toLocaleString()}</small></div>`).join(''):'<p>还没有对话记录。</p>';$('#favoriteList').innerHTML=favorites.length?favorites.map(x=>`<div><span>${escapeHtml(x.title)}</span><small>${escapeHtml(x.content.slice(0,55))}</small></div>`).join(''):'<p>点击回答下方“收藏”即可保存。</p>'}
let currentQuestion=null,practiceHints=0;async function loadPractice(){currentQuestion=await fetch('/api/practice/next/'+currentStudent).then(r=>r.json());practiceHints=0;$('#practiceConcept').textContent=currentQuestion.concept_id+' · 难度 '+Math.round(currentQuestion.difficulty*100);$('#practiceQuestion').textContent=currentQuestion.question;$('#practiceAnswer').value='';$('#practiceResult').innerHTML='';const wrong=await fetch('/api/wrong-book/'+currentStudent).then(r=>r.json());$('#wrongList').innerHTML=wrong.length?wrong.slice(0,8).map(x=>`<div><span>${x.question}</span><small>${x.error_type}</small></div>`).join(''):'<p>暂无错题，继续保持。</p>'}$('#hintPractice').onclick=()=>{practiceHints++;$('#practiceResult').innerHTML='<p>提示：先定位公式或运算规律，再检查符号和单位。</p>'};$('#submitPractice').onclick=async()=>{if(!currentQuestion)return;const d=await fetch('/api/practice/submit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({student_id:currentStudent,question_id:currentQuestion.id,answer:$('#practiceAnswer').value,hints:practiceHints})}).then(r=>r.json());$('#practiceResult').innerHTML=`<div class="result ${d.correct?'correct':'wrong'}"><b>${d.correct?'回答正确':'需要再想想'}</b><p>${d.explanation}</p><span>当前掌握度 ${d.mastery}%${d.error_type?' · '+d.error_type:''}</span></div><button class="miniBtn" onclick="loadPractice()">下一题</button>`};
$('#imageInput').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;$('#ocrBox').classList.add('show');$('#ocrStatus').textContent='正在识别题目图片…';const reader=new FileReader();reader.onload=async()=>{const d=await fetch('/api/ocr',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image_base64:reader.result})}).then(r=>r.json());if(d.text){$('#query').value=d.text;$('#ocrStatus').textContent=`${d.engine} · 请检查识别结果`}else{$('#ocrStatus').textContent=d.message||'请手动输入题干进行校正'}};reader.readAsDataURL(file)});$('#ocrClose').onclick=()=>$('#ocrBox').classList.remove('show');
$('#loginButton').onclick=async()=>{const status=$('#loginStatus');status.textContent='正在验证…';const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({user_id:$('#loginId').value.trim(),password:$('#loginPassword').value})});const d=await r.json();if(!r.ok){status.textContent=d.detail||'登录失败';return}currentStudent=d.user.id;$('#userSelect').value=currentStudent;status.textContent=`已登录：${d.user.name}，会话有效期 8 小时`;loadHistory()};
$('#addKnowledge').onclick=async()=>{const status=$('#kbStatus'),id=$('#kbId').value.trim(),name=$('#kbName').value.trim(),definition=$('#kbDefinition').value.trim();if(!id||!name||definition.length<10){status.textContent='请填写 ID、名称和至少 10 字的定义。';return}status.textContent='正在清洗与重新索引…';const r=await fetch('/api/teacher/knowledge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,name,subject:'数学',grade:'八年级',definition,example:`${name}的课堂示例`,mistake:`注意区分${name}的适用条件`,practice:`请解释${name}并举例`,source:'教师工作台'})});const d=await r.json();status.textContent=r.ok?`已生成版本 ${d.version||'latest'}，检索索引已更新`:(d.detail||'新增失败');if(r.ok)loadTeacher()};
